### ISSUE TITLE
testify to depend on testy?

### ISSUE THREAD

**Issue by bukzor** [jimr/testy#1]
We like your idea of separating these useful things out of the testify framework.
I'd like to see a future where testify depends on such a package.

Would you rather we re-use your work here, and add our updates, or start anew?

**Comment by jimr** [comment]
I think this would be a good place to start. Feel free to fork, or we could make a 'testify' organisation and move this under there...

**Comment by bukzor** [comment]
Sorry but I don't understand.  What pain would the testify organization relieve?

The main sticking point is pypi. In order to get something on pypi that we can use directly, we'd either need to rename the package which will make merging a pain, or get you to add one of us as Owner for testy.

Would you rather maintain more or less control of testy-proper?

**Comment by jimr** [comment]
I'm happy to continue maintaining. Let me know who you would like to get access on PyPI and I'll set it up.

I thought a separate org you owned might make assigning commit rights easier for you, but you can obviously do that just as easily with a fork. Whether it's worth it probably depends on how many spin-off projects there will be... 

Do you have an existing process for releases of Testify? E.g. all changes pushed to master with an appropriate tag before distributing?

**Comment by bukzor** [comment]
Our accounts are:  Yelp    bukzor

This is the github org that owns testify https://github.com/Yelp
Would it make sense to co-opt you and testy into there?

It's almost certainly premature to make any major changes yet, but I just wanted to talk about what such a plan might look like.

**Comment by jimr** [comment]
Aye, I don't really mind where it lives provided I retain commit access. Let me know once you've got a plan & need to move things forward but I'm flexible.
